services:
  db:
    image: mysql:8.0
    container_name: task-manager-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3306:3306"

    volumes:
      - task_manager_db_data:/var/lib/mysql

volumes:
  task_manager_db_data:
